pipeline {
    options {
        // set a timeout of 30 minutes for this pipeline
        timeout(time: 30, unit: 'MINUTES')
    }
    agent {
      node {
       label 'master'
      }
    }
    tools {
        maven 'Maven-3.6.2'
    }

    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
                sh "mvn --version"
            }
        }

        stage('stage 1') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                                echo "stage 1: using project: ${openshift.project()} in cluster ${openshift.cluster()}"
                        }
                    }
                }
            }
        }

        // TODO: ADD A STAGE THAT SAYS HELLO
        stage('stage 2') {
          steps {
              sh 'echo hello from stage 2!'
            }
        }
        // TODO: ADD AN APPROVAL STAGE
        stage('manual approval') {
          steps {
              timeout(time: 60, unit: 'MINUTES') {
                    input message: "Move to stage 3?"
                    }
            }
        }
        stage('stage 3') {
            steps {
                sh 'echo hello from stage 3!. This is the last stage...'
            }
        }

    }
}
